-- Create Amenities Table
CREATE TABLE IF NOT EXISTS amenities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT, -- e.g., 'Trees', 'Pool', 'Gym' (matches Lucide icon names)
  image_url TEXT, -- For carousel or visual representation
  "order" INTEGER DEFAULT 0 -- For sorting display
);

-- Enable RLS
ALTER TABLE amenities ENABLE ROW LEVEL SECURITY;

-- Policies
-- Allow public read access (SELECT)
CREATE POLICY "Public amenities take read access"
ON amenities FOR SELECT
TO public
USING (true);

-- Allow authenticated users to insert (INSERT)
CREATE POLICY "Authenticated users can insert amenities"
ON amenities FOR INSERT
TO authenticated
WITH CHECK (true);

-- Allow authenticated users to update (UPDATE)
CREATE POLICY "Authenticated users can update amenities"
ON amenities FOR UPDATE
TO authenticated
USING (true);

-- Allow authenticated users to delete (DELETE)
CREATE POLICY "Authenticated users can delete amenities"
ON amenities FOR DELETE
TO authenticated
USING (true);
