-- COMPREHENSIVE SCHEMA UPDATE
-- Run this to ensure your database allows saving all new fields.

-- 1. Update PROJECTS table with potentially missing columns
DO $$
BEGIN
    -- Add 'rera' if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'rera') THEN
        ALTER TABLE public.projects ADD COLUMN rera text;
    END IF;

    -- Add 'status' if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'status') THEN
        ALTER TABLE public.projects ADD COLUMN status text DEFAULT 'Available';
    END IF;

    -- Add 'theme_color' if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'theme_color') THEN
        ALTER TABLE public.projects ADD COLUMN theme_color text;
    END IF;

    -- Add 'gallery' if it doesn't exist (it should, but safety first)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'gallery') THEN
        ALTER TABLE public.projects ADD COLUMN gallery jsonb DEFAULT '[]'::jsonb;
    END IF;
END $$;

-- 2. Ensure AMENITIES table exists (for the "No global amenities found" issue)
CREATE TABLE IF NOT EXISTS public.amenities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  icon text, -- Lucide icon name
  image_url text,
  "order" integer default 0
);

-- 3. Enable RLS for Amenities if created
ALTER TABLE public.amenities ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for Amenities (if they don't exist, this might error if dupes, so we drop first to be clean or use conditional logic)
-- Simplified approach: Drop existing policies to recreate them ensuring they are correct
DROP POLICY IF EXISTS "Allow public read access" ON public.amenities;
CREATE POLICY "Allow public read access" ON public.amenities FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin full access" ON public.amenities;
CREATE POLICY "Allow admin full access" ON public.amenities FOR ALL USING (auth.role() = 'authenticated');

-- 5. Create Storage Bucket for 'amenities' if needed (Logic usually handled in UI, but this is a reminder)
-- Note: You should check your Storage in Supabase Dashboard and ensure 'amenities' bucket exists or reuse 'projects'.

-- Verification
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'projects';
