-- Create Banners Table
create table public.banners (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  subtitle text,
  description text,
  image_url text not null,
  link text default '/projects',
  "order" integer default 0
);

-- Create Projects Table
create table public.projects (
  id text primary key, -- slug (e.g., 'duet', 'atmos')
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  category text,
  location text,
  price text,
  status text default 'Available',
  image text not null, -- Hero image
  description text,
  overview text,
  features jsonb default '[]'::jsonb, -- Array of strings
  amenities jsonb default '[]'::jsonb, -- Array of strings
  master_layout text,
  floor_plans jsonb default '[]'::jsonb, -- Array of URLs
  gallery jsonb default '[]'::jsonb, -- Array of URLs
  theme_color text -- Hex Code
);

-- Create Leads Table
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  email text,
  project_id text references public.projects(id),
  message text,
  status text default 'New'
);

-- Enable Row Level Security (RLS)
alter table public.banners enable row level security;
alter table public.projects enable row level security;
alter table public.leads enable row level security;

-- Create Policies (Public Read, Admin Write)
-- Allow public read access to banners and projects
create policy "Allow public read access" on public.banners for select using (true);
create policy "Allow public read access" on public.projects for select using (true);

-- Allow authenticated (admin) users to insert/update/delete
create policy "Allow admin full access" on public.banners for all using (auth.role() = 'authenticated');
create policy "Allow admin full access" on public.projects for all using (auth.role() = 'authenticated');
create policy "Allow admin full access" on public.leads for select using (auth.role() = 'authenticated');

-- Allow public to insert leads (Enquiry forms)
create policy "Allow public insert" on public.leads for insert with check (true);

-- Storage Policies (if not already set)
-- NOTE: You need to create a bucket named 'projects' in Storage first.
-- These are hypothetical examples if you can run SQL for storage policies (Supabase sometimes requires UI for this)
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'projects' );
-- create policy "Auth Upload" on storage.objects for insert using ( bucket_id = 'projects' and auth.role() = 'authenticated' );
