-- Create leads table if it doesn't exist (Idempotent)
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    message TEXT,
    project_id TEXT, -- Can be linked to a project slug
    status TEXT DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Closed', 'Junk'))
);

-- Enable RLS
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow public insert to leads" ON leads;
DROP POLICY IF EXISTS "Allow authenticated read access" ON leads;
DROP POLICY IF EXISTS "Allow authenticated update access" ON leads;
DROP POLICY IF EXISTS "Allow authenticated delete access" ON leads;

-- Create Policies
-- 1. Allow anonymous users to INSERT (Sign up / Contact forms) - CRITICAL FOR PUBLIC FORMS
CREATE POLICY "Allow public insert to leads" 
ON leads FOR INSERT 
TO anon 
WITH CHECK (true);

-- 2. Allow admins (authenticated) to READ all leads
CREATE POLICY "Allow authenticated read access" 
ON leads FOR SELECT 
TO authenticated 
USING (true);

-- 3. Allow admins (authenticated) to UPDATE leads
CREATE POLICY "Allow authenticated update access" 
ON leads FOR UPDATE 
TO authenticated 
USING (true);

-- 4. Allow admins (authenticated) to DELETE leads
CREATE POLICY "Allow authenticated delete access" 
ON leads FOR DELETE 
TO authenticated 
USING (true);
