import jsPDF from 'jspdf';
import { projectsRegistry as projects } from '../data/projects';
import type { Project } from '../lib/types';

export const brochureGenerator = {
    async generateCustomBrochure(userName: string = 'Valued Partner') {
        const doc = new jsPDF('p', 'mm', 'a4');
        const viewedIds = JSON.parse(localStorage.getItem('lr_recently_viewed') || '[]');
        
        // Filter projects the user actually cared about
        const interestedProjects = projects.filter((p: Project) => viewedIds.includes(p.id));
        
        // Cover Page
        doc.setFillColor(31, 41, 55); // Secondary color
        doc.rect(0, 0, 210, 297, 'F');
        
        doc.setTextColor(197, 160, 89); // Accent color
        doc.setFont('times', 'bold');
        doc.setFontSize(40);
        doc.text('LIFE REPUBLIC', 105, 100, { align: 'center' });
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'normal');
        doc.text(`A PERSONALIZED PORTFOLIO FOR`, 105, 120, { align: 'center' });
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(userName.toUpperCase(), 105, 130, { align: 'center' });
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(156, 163, 175);
        doc.text('Generated by the Sovereign AI Concierge', 105, 280, { align: 'center' });

        // Township Vision Page
        doc.addPage();
        doc.setTextColor(31, 41, 55);
        doc.setFontSize(24);
        doc.setFont('times', 'bold');
        doc.text('Township Intelligence', 20, 30);
        
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text([
            'Kolte Patil Life Republic is a 390-acre sustainable ecosystem.',
            'Your selection of projects reflects an interest in premium spatial',
            'harmony and long-term ROI in the Hinjewadi IT Park corridor.',
            '',
            '• 150ft Wide Spine Road Connectivity',
            '• 3.5 Acre Central Urban Park',
            '• Multi-tier Sovereign Security Infrastructure',
            '• Integrated Global Education Hub (Anisha Global School)'
        ], 20, 50);

        // Individual Project Pages
        for (const project of interestedProjects) {
            doc.addPage();
            doc.setFontSize(20);
            doc.setFont('times', 'bold');
            doc.text(project.title, 20, 30);
            
            doc.setFontSize(12);
            doc.setTextColor(197, 160, 89);
            doc.text(`${project.category} | ${project.price}`, 20, 40);
            
            doc.setTextColor(107, 114, 128);
            doc.setFontSize(10);
            const splitDescription = doc.splitTextToSize(project.description || '', 170);
            doc.text(splitDescription, 20, 55);
            
            // Features
            doc.setTextColor(31, 41, 55);
            doc.setFont('helvetica', 'bold');
            doc.text('Key Features:', 20, 100);
            doc.setFont('helvetica', 'normal');
            doc.text(project.features.slice(0, 5).map((f: string) => `• ${f}`), 20, 110);
            
            // Note: In a real production app, we would use html2canvas to capture 
            // the actual floor plans from hidden DOM elements for high-fidelity images.
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text('*Prices and availability are subject to site verification.', 20, 280);
        }

        // Closing Page
        doc.addPage();
        doc.setFillColor(31, 41, 55);
        doc.rect(0, 0, 210, 297, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.text('READY FOR SPATIAL SYNTHESIS?', 105, 130, { align: 'center' });
        doc.text('Reply to our email or visit life-republic.in to book a site visit.', 105, 145, { align: 'center' });
        
        doc.save(`Life_Republic_Portfolio_${userName.replace(/\s/g, '_')}.pdf`);
    }
};
